package:
  name: shiny_app
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.1") }}

source:
  path: .

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  script:
    - $PYTHON setup.py install
  entry_points:
    - start_shiny = cli.start_shiny:start_shiny
    - copy_s3 = cli.copy_s3:copy_s3
    - make_docker = cli.make_docker:make_docker
    - create_base = cli.create_base:create_base
    - make_ami = cli.make_ami:make_ami

requirements:
  build:
    - python>=3.9
    - setuptools
  run:
    - python>=3.9