package:
  name: shiny_aws_bsis
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.1") }}

source:
  path: .

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  script:
    - $PYTHON setup.py install
  entry_points:
    - start_bsis = cli.start_bsis:start_bsis

requirements:
  build:
    - python>=3.9
    - setuptools
  run:
    - python>=3.9